### PR TITLE
portals: no retail account creation if no brand sip domain

### PR DESCRIPTION
**Pull request by manfer**
Disallow creation of retail account if brand has not a SIP domain

### CODE REVIEW

**Comment by Kaian** [comment]
This check is ok, but you're displaying an error to a company/retail admin that refers to a Brand missconfiguration. I think they shouldn't be aware of Brand existance at all, and they can not fix the problem.

The error itself is enabling Retail Feature in Brand while leaving sip domain, empty so I think the correct place for checking this will be the Brand mapper, after saving. I not sure I we can also change domain field visibility in Brand configuration screen if Features select has Retail enabled. It's better to have an extrra mandatory field rather than an error after saving.

Thanks @manfer !

**Comment by Kaian** [comment]
Oh, Retail administations can not create new accounts, my bad!

Still think this should be checked where the source of the problem is.

**Comment by mmadariaga** [comment]
I agree with @Kaian. We could ensure that domain field is never updated to an empty value that way.

**Comment by manfer** [comment]
I agree. The logic should be on Brands creation.

- If Retail Feature is enable, sip domain must be visible and required.
- If Retail Feature is disable, sip domain must be invisible and not required.

**Comment by Kaian** [comment]
I know how to do this with fields with static values (like the Route Type selectbox of a lot of screens), but not sure how to do it when values are loaded from a mapper (like Features multiselectbox).

According to [klear documentation (es)](http://irontec.github.io/klear-tutorial/yaml/fields/select.html) this could be possible, but we have to do some research :sweat_smile:

**Comment by Kaian** [comment]
Although documentation mentions select, not multiselect :-/

**Comment by mmadariaga** [comment]
VisualFilter attribute is handled only by select fields. Let me try to implement it

**Comment by mmadariaga** [comment]
There is no documentation yet but the functionality has been already implemented  in https://github.com/irontec/klearMatrix/commit/36f3b20ea1293990b5505c99e64e3c23ad456f93. 

Feel free to apply it or just throw the exception and we'll take it from that point. An example below:
>     FeaturesRelBrands:
>      title: _('Features')
>      type: multiselect
>      source:
>        data: mapper
>        config:
>          extraDataAttributes:
>            featureId: id
>          relationMapper: \IvozProvider\Mapper\Sql\FeaturesRelBrands
>          relatedMapperName: \IvozProvider\Mapper\Sql\Features
>          relationProperty: Feature
>          relatedFieldName:
>            fields:
>              - name
>            template: '%name%'
>          visualFilter:
>            iden:
>               retail:
>               toggle:
>                 - domain_users
>             recordings:
>               toggle:
>                 - recordingsLimitMB
>                 - recordingsDiskUsage
>                 - recordingsLimitEmail
>             billing:
>               toggle:
>                 - postalAddress
>                 - postalCode
>                 - town
>                 - province
>                 - country
>                 - registryData
>         order: name

**Comment by manfer** [comment]
I have not been able to make it work so could you take this one from here? If you want you can close this pull request and open a new one.

Thanks.

**Comment by mmadariaga** [comment]
Sure, Thanks

**Comment by mmadariaga** [comment]
Closed in favour of https://github.com/irontec/ivozprovider/pull/307

**Pull request closed without merging**
