### PR TITLE
User mass importer improved validations

### PR DESCRIPTION
**Pull request by mmadariaga**
Static CSV validation before the importer is run.

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX)

### CODE REVIEW

**Comment by ironArt3mis** [comment]
Rebase completed.

**Review by cruzccl — CHANGES_REQUESTED** [review]
Pending:

- Empty terminalModel: set terminalModelId to terminal with iden='Generic' (if it doesn't exist, leave it NULL).
- Empty countryCode: set DDIs.countryId to Companies.countryId. If NULL, set to Brands.countryId (this logic already exists somewhere).

**Review by Kaian — APPROVED** [review]

**Comment by ironArt3mis** [comment]
Rebase completed.

**Comment by cruzccl** [comment]
- Change 'country not found' exception in https://github.com/irontec/ivozprovider/blob/83a2e0960e359596fe8ea0e2be12173ab852390e/library/Ivoz/Provider/Domain/Service/Ddi/DdiFactory.php#L47

  with
`$country = $company->getCountry();`

- Update remaining fields on match:
  - If Name+Lastname found, update email.
  - If email found (this logic does not exist now), update Name+Lastname.
  - If terminalName found, update password, model and mac.
  - If mac found, update terminalName, password and model.

**Review by Kaian — APPROVED** [review]

**Review by cruzccl — APPROVED** [review]

**Pull request merged**
