### PR TITLE
i18n Catalan translation 

### LINKED ISSUE #1074: Catalan language support
HI,
Only to inform to community that I'm going to translate the web admin portal ( po file) to Catalan language.

If anyone have started this job an can share all done work, would be fine :)

I'm going to follow https://github.com/irontec/ivozprovider/issues/1040#issuecomment-506787502

Thanks and best sips

### PR DESCRIPTION
**Pull request by gil-obradors**
#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [ ] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [X] Fixes an existing issue (Fixes #1074) 

#### Description

First traduction to Catalan

#### Additional information

#1074

### CODE REVIEW

**Comment by gil-obradors** [comment]
Maybe the headers must be reviewed

**Comment by Kaian** [comment]
Hi @gil-obradors 

Good job with all the translations!
Our tests have detected some of the string changed since you started working on the translation files. Check this commit: https://github.com/irontec/ivozprovider/commit/9b44055063d94510656e8e8145f573d91ea9b305

Could you provide the translation in a comment for:

- Call waiting
- From 1 to 3 digits ended by # symbol
- Limits received calls when already handling this number of calls. Set 0 for disabling.

I will include them in the final file and create a final commit with all translations of the PR.

Thanks!

**Comment by gil-obradors** [comment]
- Call waiting 
> Trucada en espera
- From 1 to 3 digits ended by # symbol 
> D'1 a 3 dígits acabat amb el símbol '#'
- Limits received calls when already handling this number of calls. Set 0 for disabling.  
> Limita el número de truades entrants quant aquest  sigui superat. Configura 0 per desactivar.

**Comment by Kaian** [comment]
>Limita el número de truades entrants quant aquest sigui superat. Configura 0 per desactivar.

From the total ignorance, is _truades_ correct here? Maybe _trucades_?

**Comment by gil-obradors** [comment]
Yes sorry :S

**Comment by Kaian** [comment]
Thanks for the contribution!

**Pull request merged**
