### PR TITLE
mappers: fixed recording path issues

### PR DESCRIPTION
**Pull request by mmadariaga**
This PR fixes https://github.com/irontec/ivozprovider/issues/49

### CODE REVIEW

**Comment by Kaian** [comment]
Could we do the same for `Locutions` table? :heart:

**Comment by mmadariaga** [comment]
@Kaian You've got it

**Comment by Kaian** [comment]
In order to create an script that moves existing Recordings and Locutions to their final patch, can you confirm me this logic?

```
If id < 10 dir = 0;
if id > 10 dir = each digit of id separated by '/'
```

**Comment by Kaian** [comment]
Umm maybe I can come with a better logic:
```
Remove all digits but last of the id and create a folder with those splited.
If no digit has been removed (because id only has one digit) create a dir with 0.
```

**Comment by mmadariaga** [comment]
@kaian You can check out the logic applied here https://github.com/irontec/klear-library/blob/chloe/Model/Fso/Adapter/StoragePathResolver/Default.php#L182

Your second approach sound good :)

**Pull request merged**
