### PR TITLE
Enum constants

### PR DESCRIPTION
**Pull request by mmadariaga**
Make enums entity class constants

### CODE REVIEW

**Comment by Kaian** [comment]
I love this <3

It would be possible to remove the word CHOICE from non-array constants? I think its more readable without that word.

Thanks!

**Comment by mmadariaga** [comment]
Removing CHOICE from constant name would make impossible to have an enum with 'choices' value. Plus It reflects that the possible values are restricted and I don't really dislike it :)

Your call @cruzccl  ;)

**Comment by Kaian** [comment]
Now you have no CHOICE but remove CHOICE from the constants. At least we agreed that CHOICE was not the best CHOICE for the variable identification tag and type was redundant for some fields names, so it wasn't a good CHOICE either.

😜

**Comment by mmadariaga** [comment]
Having not a single CHOICE turned out to be a good CHOICE

**Comment by ironArt3mis** [comment]
Rebase completed.

**Pull request merged**
